import { expect, test } from "@playwright/test";
import { ensureSystemCategories } from "./helpers/categories";
import {
  applySessionCookie,
  deleteSeededUser,
  seedUserWithSession,
  type SeededUser,
} from "./helpers/auth";

/**
 * Photo attachments, end to end.
 *
 * ## The fixture
 *
 * `public/icons/icon-192.png` — already committed, synthetic, generated by
 * `npm run icons:generate`. **This is a public repository and a real photo must
 * never be added to it**, so the upload fixture is a file that is already here
 * and contains nothing personal.
 *
 * The image is 192px, well inside the 1600px limit, so the browser leaves it
 * alone — which also exercises the "already small enough" branch of the
 * downscaler for free.
 */

const FIXTURE = "public/icons/icon-192.png";

let seeded: SeededUser;

test.beforeEach(async ({ context, baseURL }) => {
  seeded = await seedUserWithSession();
  await ensureSystemCategories();
  await applySessionCookie(context, seeded.sessionToken, baseURL ?? "http://localhost:3000");
});

test.afterEach(async () => {
  await deleteSeededUser(seeded.userId);
});

/**
 * Fills the amount and picks a category.
 *
 * The category is NOT optional: only the `?type=fuel` entry point preselects
 * one (it matches the seeded system "Fuel" row), so a plain "Add expense" form
 * has an empty required select and the browser silently refuses to submit —
 * which looks exactly like the page not loading.
 */
async function fillExpense(page: import("@playwright/test").Page, amount: string) {
  await page.getByLabel("Amount (€)").fill(amount);
  await page.getByLabel("Category").selectOption({ index: 1 });
}

/** Creates a car and returns its id, straight through the UI. */
async function createCar(page: import("@playwright/test").Page, plate: string): Promise<string> {
  await page.goto("/cars/new");
  await page.getByLabel("Licence plate").fill(plate);
  await page.getByRole("button", { name: /Add car|Save/ }).click();
  await expect(page).toHaveURL(/\/cars$/);

  const href = await page.getByRole("link", { name: "Expenses" }).first().getAttribute("href");
  return href!.split("/")[2];
}

test.describe("attaching a photo", () => {
  test("stores it with the expense and serves it back", async ({ page }) => {
    // AC-1.
    const carId = await createCar(page, "ATTACH-01");

    await page.goto(`/cars/${carId}/expenses/new?type=fuel`);
    await page.getByLabel("Amount (€)").fill("52.10");
    await page.getByLabel(/^Photo/).setInputFiles(FIXTURE);
    await page.getByRole("button", { name: "Add fuel" }).click();

    await expect(page).toHaveURL(/\/cars\/[^/]+\/expenses$/);

    // The photo lives on the edit page, where it can also be removed.
    await page.getByRole("link", { name: "Edit" }).first().click();

    const photo = page.getByRole("region", { name: "Photos" }).getByRole("img");
    await expect(photo).toBeVisible();

    // ⚠️ toBeVisible() is NOT enough on its own: a broken image still has a
    // non-empty box, and this assertion passed against a 320x2 element that had
    // not loaded at all. naturalWidth is what proves the served bytes actually
    // decode into an image.
    await expect
      .poll(() => photo.evaluate((el: HTMLImageElement) => el.naturalWidth))
      .toBeGreaterThan(0);

    // The stored dimensions reach the markup, so the space is reserved rather
    // than the layout jumping when the photo arrives.
    await expect(photo).toHaveAttribute("width", /^\d+$/);
    await expect(photo).toHaveAttribute("height", /^\d+$/);

    const src = await photo.getAttribute("src");
    expect(src).toMatch(/^\/api\/attachments\/[^/]+$/);

    // Served by the route, not from a public path.
    const response = await page.request.get(src!);
    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toContain("image/");
    expect(response.headers()["cache-control"]).toContain("no-store");
  });

  test("removes the photo when asked", async ({ page }) => {
    const carId = await createCar(page, "ATTACH-02");

    await page.goto(`/cars/${carId}/expenses/new`);
    await fillExpense(page, "10.00");
    await page.getByLabel(/^Photo/).setInputFiles(FIXTURE);
    await page.getByRole("button", { name: "Add expense" }).click();

    await page.getByRole("link", { name: "Edit" }).first().click();
    const src = await page
      .getByRole("region", { name: "Photos" })
      .getByRole("img")
      .getAttribute("src");

    await page.getByRole("button", { name: "Remove photo" }).click();

    await expect(page.getByRole("region", { name: "Photos" })).toHaveCount(0);

    // And the route stops serving it — the object is gone, not just hidden.
    const response = await page.request.get(src!);
    expect(response.status()).toBe(404);
  });

  test("shrinks an oversized photo in the browser before uploading it", async ({
    page,
    browser,
  }) => {
    // AC-4, and the reason the whole design exists: a Vercel serverless request
    // body caps at 4.5 MB and a phone photo is routinely 3–6 MB.
    //
    // ⚠️ Every other test here uses the 192px icon, which is ALREADY within the
    // limit — so they exercise the "leave it alone" branch and prove nothing
    // about downscaling. This one needs a genuinely oversized image, generated
    // rather than committed: a real photo must never enter a public repository.
    const big = "/tmp/gaspense-oversized.png";
    const canvas = await browser.newContext({ viewport: { width: 4000, height: 3000 } });
    try {
      const painter = await canvas.newPage();
      // Noise, not a flat colour — a solid image compresses to almost nothing
      // and would not test the size path at all.
      await painter.setContent(`<body style="margin:0">
        <div style="width:4000px;height:3000px;background:
          repeating-linear-gradient(45deg,#c00 0 7px,#0c0 7px 14px,#00c 14px 21px)"></div>
      </body>`);
      await painter.screenshot({ path: big });
    } finally {
      await canvas.close();
    }

    const carId = await createCar(page, "ATTACH-06");
    await page.goto(`/cars/${carId}/expenses/new?type=fuel`);
    await page.getByLabel("Amount (€)").fill("40.00");
    await page.getByLabel(/^Photo/).setInputFiles(big);

    // The field says so when it has resized something.
    await expect(page.getByRole("status")).toContainText(/Resized for upload/);

    await page.getByRole("button", { name: "Add fuel" }).click();
    await page.getByRole("link", { name: "Edit" }).first().click();

    const photo = page.getByRole("region", { name: "Photos" }).getByRole("img");
    await expect(photo).toBeVisible();

    const src = await photo.getAttribute("src");
    const response = await page.request.get(src!);

    // Re-encoded as JPEG whatever went in, and comfortably under the body cap.
    expect(response.headers()["content-type"]).toBe("image/jpeg");
    const bytes = (await response.body()).byteLength;
    expect(bytes).toBeLessThan(2 * 1024 * 1024);
    expect(bytes).toBeGreaterThan(0);
  });

  test("an expense with no photo shows no photo section", async ({ page }) => {
    // The negative control: without it, "the photo appears" could be satisfied
    // by a section that is always there.
    const carId = await createCar(page, "ATTACH-03");

    await page.goto(`/cars/${carId}/expenses/new`);
    await fillExpense(page, "7.50");
    await page.getByRole("button", { name: "Add expense" }).click();

    await page.getByRole("link", { name: "Edit" }).first().click();
    await expect(page.getByRole("region", { name: "Photos" })).toHaveCount(0);
  });
});

test.describe("attachment isolation", () => {
  test("another user gets 404, never the bytes", async ({ page, browser, baseURL }) => {
    // AC-3. 404 and not 403: a 403 would confirm the id exists.
    const carId = await createCar(page, "ATTACH-04");

    await page.goto(`/cars/${carId}/expenses/new`);
    await fillExpense(page, "33.00");
    await page.getByLabel(/^Photo/).setInputFiles(FIXTURE);
    await page.getByRole("button", { name: "Add expense" }).click();

    await page.getByRole("link", { name: "Edit" }).first().click();
    const src = await page
      .getByRole("region", { name: "Photos" })
      .getByRole("img")
      .getAttribute("src");

    // A second, entirely separate account.
    const intruder = await seedUserWithSession();
    const context = await browser.newContext();
    try {
      await applySessionCookie(context, intruder.sessionToken, baseURL ?? "http://localhost:3000");
      const response = await context.request.get(src!);
      expect(response.status()).toBe(404);
      expect((await response.body()).byteLength).toBe(0);
    } finally {
      await context.close();
      await deleteSeededUser(intruder.userId);
    }
  });

  test("a signed-out request gets 404, never a redirect that confirms the id", async ({
    page,
    browser,
  }) => {
    const carId = await createCar(page, "ATTACH-05");

    await page.goto(`/cars/${carId}/expenses/new`);
    await fillExpense(page, "21.00");
    await page.getByLabel(/^Photo/).setInputFiles(FIXTURE);
    await page.getByRole("button", { name: "Add expense" }).click();

    await page.getByRole("link", { name: "Edit" }).first().click();
    const src = await page
      .getByRole("region", { name: "Photos" })
      .getByRole("img")
      .getAttribute("src");

    const anonymous = await browser.newContext();
    try {
      const response = await anonymous.request.get(src!, { maxRedirects: 0 });
      expect(response.status()).toBe(404);
    } finally {
      await anonymous.close();
    }
  });
});
