import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { randomUUID } from "node:crypto";

/**
 * Where attachment bytes live.
 *
 * An interface with a local filesystem adapter, because there is no Supabase
 * project yet — 04-04 adds that adapter and changes nothing else. Everything
 * above this line works against the interface, so the backend is a swap rather
 * than a rewrite.
 *
 * ## The directory is deliberately NOT under public/
 *
 * Anything in `public/` is served statically by Next with no session check.
 * Putting user photos there would make every one of them world-readable at a
 * guessable path — the exact opposite of what `/api/attachments/[id]` exists to
 * enforce. `.storage/` sits at the repository root and is gitignored.
 */

export type StoredObject = {
  body: Uint8Array;
  contentType: string;
};

export interface ObjectStorage {
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

/** Extensions for the MIME types the validator accepts. */
const EXTENSION_BY_MIME: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

/**
 * An opaque object key.
 *
 * `randomUUID` rather than anything derived from the user, the expense or the
 * uploaded filename: a key must not be guessable from something an attacker
 * knows, and a client-supplied filename is an obvious path-traversal vector.
 * The extension comes from the *validated* MIME type, never from the name.
 */
export function newStorageKey(mimeType: string): string {
  const extension = EXTENSION_BY_MIME[mimeType];
  if (!extension) throw new Error(`Refusing to build a key for MIME type: ${mimeType}`);

  return `${randomUUID()}.${extension}`;
}

/** Local filesystem storage. The default until 04-04 wires Supabase. */
export function createLocalStorage(root: string): ObjectStorage {
  const rootPath = resolve(root);

  /**
   * Resolves a key inside the root and refuses anything that escapes it.
   *
   * Keys are generated by `newStorageKey` and cannot contain a separator, so
   * this is belt and braces — but a path check that only runs when the caller
   * is trusted is a path check that stops running the day someone else calls it.
   */
  const pathFor = (key: string): string => {
    const target = resolve(join(rootPath, key));
    if (target !== rootPath && !target.startsWith(rootPath + "/")) {
      throw new Error("Refusing a storage key that escapes the storage root");
    }
    return target;
  };

  const contentTypePath = (key: string) => `${pathFor(key)}.type`;

  return {
    async put(key, body, contentType) {
      const target = pathFor(key);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, body);
      // The content type travels beside the object rather than being guessed
      // from the extension on the way out — the serving route must echo what was
      // validated on the way in, not re-derive it.
      await writeFile(contentTypePath(key), contentType, "utf8");
    },

    async get(key) {
      try {
        const [body, contentType] = await Promise.all([
          readFile(pathFor(key)),
          readFile(contentTypePath(key), "utf8"),
        ]);
        return { body: new Uint8Array(body), contentType: contentType.trim() };
      } catch {
        // A missing object is an ordinary outcome — the row and the object can
        // disagree — so it is reported, not thrown.
        return null;
      }
    },

    async delete(key) {
      await Promise.all([
        rm(pathFor(key), { force: true }),
        rm(contentTypePath(key), { force: true }),
      ]);
    },
  };
}

/** Root for the local adapter. Overridable so tests get a temporary directory. */
const localRoot = () => process.env["STORAGE_LOCAL_ROOT"] ?? resolve(process.cwd(), ".storage");

let cached: ObjectStorage | null = null;
let cachedRoot: string | null = null;

/**
 * The configured storage backend.
 *
 * Cached per root rather than per process: the integration suite points
 * `STORAGE_LOCAL_ROOT` at a temporary directory, and a module-scope singleton
 * would hand it the developer's `.storage/` instead — the same shape of bug
 * Phase 8 found with module-scope Prisma clients.
 */
export function getStorage(): ObjectStorage {
  const root = localRoot();
  if (!cached || cachedRoot !== root) {
    cached = createLocalStorage(root);
    cachedRoot = root;
  }
  return cached;
}
