-- Links an odometer reading to the expense it was captured with.
--
-- `source: EXPENSE` alone recorded only that a reading came from *some*
-- fill-up. That is not enough to maintain the pair: matching back on
-- (carId, date) is ambiguous, because two fill-ups on one day are ordinary,
-- and editing an expense's date would orphan its reading.
--
-- Nullable: a manually entered reading has no expense.
-- Unique: one expense captures at most one reading.
-- ON DELETE CASCADE: a reading must never outlive the fill-up it claims to
-- measure. A stale one would silently corrupt the consumption series that
-- Phase 3 computes from consecutive full-tank readings.
--
-- SQL generated by `prisma migrate diff` from schema.prisma, not hand-written.

-- AlterTable
ALTER TABLE "OdometerReading" ADD COLUMN     "expenseId" TEXT;
-- CreateIndex
CREATE UNIQUE INDEX "OdometerReading_expenseId_key" ON "OdometerReading"("expenseId");
-- AddForeignKey
ALTER TABLE "OdometerReading" ADD CONSTRAINT "OdometerReading_expenseId_fkey" FOREIGN KEY ("expenseId") REFERENCES "Expense"("id") ON DELETE CASCADE ON UPDATE CASCADE;
